FROM alpine:3.8

WORKDIR /var/www/html

ARG PHP_VERSION=7.2.13
ENV PHP_ERROR_REPORTING="E_ALL & ~E_DEPRECATED & ~E_STRICT"
ENV PHP_INPUT_NESTING_LIMIT=32
ENV PHP_INPUT_TIME_LIMIT=10
ENV PHP_INPUT_VARS_LIMIT=2048
ENV PHP_MEMORY_LIMIT=256M
ENV PHP_POST_SIZE_LIMIT=32M
ENV PHP_SOCKET_TIMEOUT=30
ENV PHP_TIMEZONE=Europe/Berlin
ENV PHP_TIME_LIMIT=30
ENV PHP_UPLOAD_FILES_LIMIT=8
ENV PHP_UPLOAD_SIZE_LIMIT=32M

COPY src /
RUN php-common-setup
ENTRYPOINT ["php-common-entrypoint"]
